# Generated by Django 3.1.5 on 2021-01-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shortanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortanswer',
            name='answer',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
